spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/jpashop
      username: sa
      password:
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create #자동으로 table을 만들어주는 옵션
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    sql: debug #jpa나 hibernate가 생성하는 SQL이 전부 보임
    org.hibernate.type: trace #쿼리 파라미터 볼수 있게 해주는 옵션